title: Mohammed Shaik | Data Scientist & ML Engineer
logo: ppp.png
description: M.S. Data Science @ GWU. Bridging the gap between complex statistical analysis and scalable software engineering.
show_downloads: True
theme: jekyll-theme-hacker
